# Generated by Django 3.1.6 on 2021-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ManyToManyField(blank=True, related_name='business_fk', to='business.Business', verbose_name='Empresas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cel',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
