# Generated by Django 3.1.6 on 2021-02-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
