# Generated by Django 3.1.6 on 2021-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cel',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
