# Generated by Django 3.1.6 on 2021-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('users', '0002_auto_20210208_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ManyToManyField(blank=True, to='business.Business', verbose_name='Empresas'),
        ),
    ]
