# Generated by Django 3.1.6 on 2021-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('users', '0003_auto_20210208_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ManyToManyField(blank=True, related_name='business_set', to='business.Business', verbose_name='Empresas'),
        ),
    ]
