# Generated by Django 3.1.6 on 2021-02-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('users', '0004_auto_20210208_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ManyToManyField(to='business.Business'),
        ),
    ]
